version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - durationcheck
    - errname
    - exhaustive
    - goconst
    - gocritic
    - godot
    - govet
    - ineffassign
    - mirror
    - musttag
    - nosprintfhostport
    - predeclared
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - goconst
          - gocritic
          - gosec
          - ineffassign
          - staticcheck
        path: (.+)_test\.go
      - linters:
          - staticcheck
        text: S1000
      - linters:
          - godot
        path: config/keys.go
      - linters:
          - nestif
        path: internal/sync/images.go
      - path: reload.go
        text: SA9003
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
